-- ============================================================================
-- PROFESSIONAL PAYMENT SYSTEM - ENTERPRISE LEVEL
-- Tranzakció-biztos fizetési rendszer
-- ============================================================================

-- 1. KÖLTSÉGEK ÉS FIZETÉS TÁMOGATÁSA
ALTER TABLE public.timesheets 
ADD COLUMN IF NOT EXISTS expense_amount numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS expense_note text,
ADD COLUMN IF NOT EXISTS payment_id bigint; -- Ha ez NULL, akkor még tartozol vele!

-- 2. FIZETÉSEK TÁBLA (A nyugta)
CREATE TABLE IF NOT EXISTS public.payments (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid REFERENCES public.profiles(id) NOT NULL,
  total_paid numeric NOT NULL,
  payment_date timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  admin_id uuid REFERENCES public.profiles(id)
);

-- 3. RIPORT FÜGGVÉNY (A "Mennyivel tartozom?" kérdésre)
CREATE OR REPLACE FUNCTION get_unpaid_report()
RETURNS TABLE (
  user_id uuid,
  full_name text,
  hourly_rate numeric,
  unpaid_hours numeric,      -- Ledolgozott órák
  unpaid_wages numeric,      -- Munkabér (óra * díj)
  unpaid_expenses numeric,   -- Anyagköltség
  total_due numeric          -- Végösszeg
) 
LANGUAGE plpgsql SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    p.id AS user_id,
    p.full_name,
    COALESCE(p.hourly_rate, 0),
    -- Órák összegzése (csak work típus és nincs kifizetve)
    COALESCE(SUM(
      CASE WHEN t.entry_type = 'work' AND t.start_time IS NOT NULL AND t.end_time IS NOT NULL THEN 
        EXTRACT(EPOCH FROM (t.end_time - t.start_time)) / 3600
      ELSE 0 END
    ), 0)::numeric(10, 2) AS unpaid_hours,
    
    -- Munkabér számítás
    (COALESCE(SUM(
      CASE WHEN t.entry_type = 'work' AND t.start_time IS NOT NULL AND t.end_time IS NOT NULL THEN 
        EXTRACT(EPOCH FROM (t.end_time - t.start_time)) / 3600
      ELSE 0 END
    ), 0) * COALESCE(p.hourly_rate, 0))::numeric(10, 0) AS unpaid_wages,

    -- Költségek összege
    COALESCE(SUM(COALESCE(t.expense_amount, 0)), 0)::numeric(10, 0) AS unpaid_expenses,

    -- Végösszeg (Bér + Költség)
    ((COALESCE(SUM(
      CASE WHEN t.entry_type = 'work' AND t.start_time IS NOT NULL AND t.end_time IS NOT NULL THEN 
        EXTRACT(EPOCH FROM (t.end_time - t.start_time)) / 3600
      ELSE 0 END
    ), 0) * COALESCE(p.hourly_rate, 0)) + COALESCE(SUM(COALESCE(t.expense_amount, 0)), 0))::numeric(10, 0) AS total_due

  FROM public.profiles p
  JOIN public.timesheets t ON t.user_id = p.id 
  WHERE 
    t.payment_id IS NULL -- CSAK AMI NINCS KIFIZETVE
    AND t.status != 'rejected'
  GROUP BY p.id, p.full_name, p.hourly_rate
  HAVING 
    COALESCE(SUM(COALESCE(t.expense_amount, 0)), 0) > 0 OR
    COALESCE(SUM(
      CASE WHEN t.entry_type = 'work' AND t.start_time IS NOT NULL AND t.end_time IS NOT NULL THEN 
        EXTRACT(EPOCH FROM (t.end_time - t.start_time)) / 3600
      ELSE 0 END
    ), 0) > 0;
END;
$$;

-- 4. BIZTONSÁGOS KIFIZETÉS FÜGGVÉNY (Tranzakció)
-- Ez a függvény egy lépésben hozza létre a nyugtát és zárja le a sorokat
CREATE OR REPLACE FUNCTION execute_payment(p_user_id uuid, p_amount numeric)
RETURNS json
LANGUAGE plpgsql SECURITY DEFINER
AS $$
DECLARE
  v_payment_id bigint;
  v_admin_id uuid;
BEGIN
  -- Admin ellenőrzés
  v_admin_id := auth.uid();
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = v_admin_id AND is_admin = true) THEN
    RAISE EXCEPTION 'Csak admin fizethet ki!';
  END IF;

  -- 1. Létrehozzuk a fizetési rekordot
  INSERT INTO public.payments (user_id, total_paid, admin_id)
  VALUES (p_user_id, p_amount, v_admin_id)
  RETURNING id INTO v_payment_id;

  -- 2. Frissítjük a timesheeteket (hozzákötjük a fizetéshez + jóváhagyás)
  UPDATE public.timesheets
  SET payment_id = v_payment_id,
      status = 'approved'
  WHERE user_id = p_user_id 
    AND payment_id IS NULL 
    AND status != 'rejected';

  RETURN json_build_object('success', true, 'payment_id', v_payment_id);
END;
$$;

-- 5. RLS POLICY-K A PAYMENTS TÁBLÁHOZ
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- Admin láthatja az összes fizetést (töröljük, ha létezik, majd újra létrehozzuk)
DROP POLICY IF EXISTS "Admin can view all payments" ON public.payments;
CREATE POLICY "Admin can view all payments"
ON public.payments FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND is_admin = true
  )
);

-- Admin hozhat létre fizetést (töröljük, ha létezik, majd újra létrehozzuk)
DROP POLICY IF EXISTS "Admin can create payments" ON public.payments;
CREATE POLICY "Admin can create payments"
ON public.payments FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND is_admin = true
  )
);

-- Felhasználó láthatja a saját fizetéseit (töröljük, ha létezik, majd újra létrehozzuk)
DROP POLICY IF EXISTS "Users can view their own payments" ON public.payments;
CREATE POLICY "Users can view their own payments"
ON public.payments FOR SELECT
USING (user_id = auth.uid());

-- 6. RÉSZLETES TÉTELLISTA FÜGGVÉNY (Drill-down nézet)
-- Egy adott ember részletes, kifizetetlen tételeinek lekérése
CREATE OR REPLACE FUNCTION get_unpaid_details_for_user(p_user_id uuid)
RETURNS TABLE (
  work_date date,
  entry_type text,
  description text,     -- Munka leírása VAGY költség leírása
  hours numeric,        -- Ledolgozott óra
  wage_amount numeric,  -- Munkadíj arra a napra
  expense_amount numeric, -- Költség arra a napra
  total_daily numeric   -- Napi összesen
) 
LANGUAGE plpgsql SECURITY DEFINER
AS $$
DECLARE
  v_hourly_rate numeric;
BEGIN
  -- Lekérjük az ember órabérét
  SELECT hourly_rate INTO v_hourly_rate FROM public.profiles WHERE id = p_user_id;

  RETURN QUERY
  SELECT 
    t.work_date,
    t.entry_type::text,  -- Enum castolása text-re
    -- Leírás összefűzése (hogy lássuk mi volt a munka és mi a költség)
    CASE 
      WHEN t.expense_amount > 0 AND t.expense_note IS NOT NULL 
        THEN COALESCE(t.note, '') || ' (+ Költség: ' || t.expense_note || ')'
      ELSE COALESCE(t.note, '') 
    END::text as description,
    
    -- Óra (csak work típusnál számít)
    CASE 
      WHEN t.entry_type = 'work' AND t.start_time IS NOT NULL AND t.end_time IS NOT NULL THEN 
        (EXTRACT(EPOCH FROM (t.end_time - t.start_time)) / 3600)::numeric(10, 2)
      ELSE 0 
    END as hours,

    -- Munkadíj (Óra * Órabér)
    (CASE 
      WHEN t.entry_type = 'work' AND t.start_time IS NOT NULL AND t.end_time IS NOT NULL THEN 
        (EXTRACT(EPOCH FROM (t.end_time - t.start_time)) / 3600) * COALESCE(v_hourly_rate, 0)
      ELSE 0 
    END)::numeric(10, 0) as wage_amount,

    -- Költség
    COALESCE(t.expense_amount, 0)::numeric(10, 0) as expense_amount,

    -- Napi Összesen (Munkadíj + Költség)
    ((CASE 
      WHEN t.entry_type = 'work' AND t.start_time IS NOT NULL AND t.end_time IS NOT NULL THEN 
        (EXTRACT(EPOCH FROM (t.end_time - t.start_time)) / 3600) * COALESCE(v_hourly_rate, 0)
      ELSE 0 
    END) + COALESCE(t.expense_amount, 0))::numeric(10, 0) as total_daily

  FROM public.timesheets t
  WHERE 
    t.user_id = p_user_id
    AND t.payment_id IS NULL -- Csak a fizetetlen
    AND t.status != 'rejected'
  ORDER BY t.work_date ASC;
END;
$$;

-- 7. JOGOSULTSÁGOK
GRANT EXECUTE ON FUNCTION get_unpaid_report() TO authenticated;
GRANT EXECUTE ON FUNCTION execute_payment(uuid, numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION get_unpaid_details_for_user(uuid) TO authenticated;
GRANT SELECT, INSERT ON public.payments TO authenticated;

-- ============================================================================
-- KÉSZ! Most már használhatod a get_unpaid_report() és execute_payment() 
-- függvényeket a frontend/backend kódban.
-- ============================================================================
