-- ============================================
-- MUNKAIDŐ NYILVÁNTARTÓ RENDSZER - ADATBÁZIS SETUP
-- ============================================
-- Futtasd le ezt a scriptet a Supabase SQL Editor-ben
-- ============================================

-- 1. PROFILOK TÁBLA (Hogy ne ID-kat láss, hanem neveket)
-- Ez a tábla automatikusan szinkronban lesz a regisztrált felhasználókkal
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  is_admin boolean default false,
  hourly_rate numeric
);

-- 2. MUNKAIDŐ TÁBLA
create table public.timesheets (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  work_date date not null default current_date,
  start_time time not null,
  end_time time not null,
  note text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. AUTOMATIZMUS (Trigger)
-- Ha valaki regisztrál, hozzunk létre neki egy profilt automatikusan
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1), 'Felhasználó')
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 4. BIZTONSÁG (Row Level Security)
alter table public.profiles enable row level security;
alter table public.timesheets enable row level security;

-- Szabályok Profilokhoz:
create policy "User lathatja a sajat profiljat" on profiles for select using (auth.uid() = id);
create policy "Admin lathatja a profilokat" on profiles for select
using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));
create policy "User módosíthatja a sajátját" on profiles for update using (auth.uid() = id);

-- Szabályok Munkaidőhöz:
-- A Dolgozó csak a sajátját látja és írhatja (nem szerkesztheti, nem törölheti)
create policy "Dolgozó látja a sajátját" on timesheets for select using (auth.uid() = user_id);
create policy "Dolgozó írhatja a sajátját" on timesheets for insert with check (auth.uid() = user_id);

-- Az ADMIN mindent lát (Itt majd a te email címedet állítjuk be adminnak)
create policy "Admin mindent lát" on timesheets for select 
using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

-- Admin törölheti a rögzítéseket
create policy "Admin törölheti" on timesheets for delete
using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

-- Admin módosíthatja a rögzítéseket
create policy "Admin módosíthatja" on timesheets for update
using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

-- ============================================
-- FONTOS: Miután regisztráltál az alkalmazásba
-- a saját email címeddel, menj vissza a Supabase
-- "Table Editor" részébe, keresd meg a `profiles` táblát,
-- és a saját sorodban pipáld be az `is_admin` mezőt!
-- Így leszel te a főnök.
-- ============================================

