-- ============================================
-- MUNKAIDŐ NYILVÁNTARTÓ RENDSZER - ADATBÁZIS SETUP (BIZTONSÁGOS)
-- ============================================
-- Ez a script ellenőrzi, hogy léteznek-e a táblák
-- Ha már léteznek, akkor nem hozza létre újra
-- ============================================

-- 1. PROFILOK TÁBLA (Hogy ne ID-kat láss, hanem neveket)
-- Ez a tábla automatikusan szinkronban lesz a regisztrált felhasználókkal
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  is_admin boolean default false,
  hourly_rate numeric
);

-- 2. MUNKAIDŐ TÁBLA
CREATE TABLE IF NOT EXISTS public.timesheets (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  work_date date not null default current_date,
  start_time time not null,
  end_time time not null,
  note text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. AUTOMATIZMUS (Trigger) - csak ha még nincs
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1), 'Felhasználó')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql security definer;

-- Trigger törlése, ha létezik, majd újra létrehozása
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 4. BIZTONSÁG (Row Level Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timesheets ENABLE ROW LEVEL SECURITY;

-- Szabályok Profilokhoz (csak ha még nincs):
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'profiles' 
    AND policyname = 'Mindenki láthatja a profilokat'
  ) THEN
    DROP POLICY "Mindenki láthatja a profilokat" ON profiles;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'profiles' 
    AND policyname = 'User lathatja a sajat profiljat'
  ) THEN
    CREATE POLICY "User lathatja a sajat profiljat" ON profiles 
    FOR SELECT USING (auth.uid() = id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'profiles' 
    AND policyname = 'Admin lathatja a profilokat'
  ) THEN
    CREATE POLICY "Admin lathatja a profilokat" ON profiles 
    FOR SELECT USING (exists (select 1 from profiles where id = auth.uid() and is_admin = true));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'profiles' 
    AND policyname = 'User módosíthatja a sajátját'
  ) THEN
    CREATE POLICY "User módosíthatja a sajátját" ON profiles 
    FOR UPDATE USING (auth.uid() = id);
  END IF;
END $$;

-- Szabályok Munkaidőhöz:
-- A Dolgozó csak a sajátját látja és írhatja (nem szerkesztheti, nem törölheti)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'timesheets' 
    AND policyname = 'Dolgozó látja a sajátját'
  ) THEN
    CREATE POLICY "Dolgozó látja a sajátját" ON timesheets 
    FOR SELECT USING (auth.uid() = user_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'timesheets' 
    AND policyname = 'Dolgozó írhatja a sajátját'
  ) THEN
    CREATE POLICY "Dolgozó írhatja a sajátját" ON timesheets 
    FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;


-- Az ADMIN mindent lát és módosíthat
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'timesheets' 
    AND policyname = 'Admin mindent lát'
  ) THEN
    CREATE POLICY "Admin mindent lát" ON timesheets 
    FOR SELECT USING (exists (select 1 from profiles where id = auth.uid() and is_admin = true));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'timesheets' 
    AND policyname = 'Admin törölheti'
  ) THEN
    CREATE POLICY "Admin törölheti" ON timesheets 
    FOR DELETE USING (exists (select 1 from profiles where id = auth.uid() and is_admin = true));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'timesheets' 
    AND policyname = 'Admin módosíthatja'
  ) THEN
    CREATE POLICY "Admin módosíthatja" ON timesheets 
    FOR UPDATE USING (exists (select 1 from profiles where id = auth.uid() and is_admin = true));
  END IF;
END $$;

-- ============================================
-- FONTOS: Miután regisztráltál az alkalmazásba
-- a saját email címeddel, menj vissza a Supabase
-- "Table Editor" részébe, keresd meg a `profiles` táblát,
-- és a saját sorodban pipáld be az `is_admin` mezőt!
-- Így leszel te a főnök.
-- ============================================


